ERROR:Cpp: LiteralExpressionLE failed to translate
DEBUG:Cpp:LiteralExpressionLE
stdout:

stderr:
LiteralExpressionLE.cpp: In member function ‘void LiteralExpressionLE_HLSM::update()’:
LiteralExpressionLE.cpp:54:40: error: ‘cond2’ was not declared in this scope
                         if( !cond2(true) ) 
                                        ^
LiteralExpressionLE.cpp:60:40: error: ‘cond2’ was not declared in this scope
                         if( !cond2(true) ) 
                                        ^
LiteralExpressionLE.cpp:64:35: error: ‘cond4’ was not declared in this scope
                         if( cond4() ) 
                                   ^
LiteralExpressionLE.cpp:70:35: error: ‘cond4’ was not declared in this scope
                         if( cond4() ) 
                                   ^

DEBUG:Cpp:1 != 0
DEBUG:Cpp:<type 'exceptions.AssertionError'>
DEBUG:Cpp:  File "Tester.py", line 119, in runTest
    self.assertEquals( exit_code, 0 )

  File "/usr/lib/python2.7/unittest/case.py", line 515, in assertEqual
    assertion_func(first, second, msg=msg)

  File "/usr/lib/python2.7/unittest/case.py", line 508, in _baseAssertEqual
    raise self.failureException(msg)

ERROR:Java: LiteralExpressionLE failed to translate
DEBUG:Java:LiteralExpressionLE
stdout:

stderr:
LiteralExpressionLEAbstractFSM.java:46: error: cannot find symbol
                    if( !cond2(true) ) 
                         ^
  symbol:   method cond2(boolean)
  location: class LiteralExpressionLEAbstractFSM
LiteralExpressionLEAbstractFSM.java:52: error: cannot find symbol
                    if( !cond2(true) ) 
                         ^
  symbol:   method cond2(boolean)
  location: class LiteralExpressionLEAbstractFSM
LiteralExpressionLEAbstractFSM.java:56: error: cannot find symbol
                    if( cond4() ) 
                        ^
  symbol:   method cond4()
  location: class LiteralExpressionLEAbstractFSM
LiteralExpressionLEAbstractFSM.java:62: error: cannot find symbol
                    if( cond4() ) 
                        ^
  symbol:   method cond4()
  location: class LiteralExpressionLEAbstractFSM
4 errors

DEBUG:Java:1 != 0
DEBUG:Java:<type 'exceptions.AssertionError'>
DEBUG:Java:  File "Tester.py", line 119, in runTest
    self.assertEquals( exit_code, 0 )

  File "/usr/lib/python2.7/unittest/case.py", line 515, in assertEqual
    assertion_func(first, second, msg=msg)

  File "/usr/lib/python2.7/unittest/case.py", line 508, in _baseAssertEqual
    raise self.failureException(msg)

ERROR:Arduino: Monster_MDP failed to translate
DEBUG:Arduino:Monster_MDP
stdout:

stderr:

DEBUG:Arduino:No JSON object could be decoded
DEBUG:Arduino:<type 'exceptions.ValueError'>
DEBUG:Arduino:  File "Tester.py", line 110, in runTest
    self.parser.parse(full_path)

  File "/mnt/c/Users/Dajin/Documents/GitHub/JFlapToCode/src/JFlapToCode.py", line 41, in parse
    self.parse_json( filename )

  File "/mnt/c/Users/Dajin/Documents/GitHub/JFlapToCode/src/JFlapToCode.py", line 68, in parse_json
    d = json.loads( raw_string )

  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)

  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())

  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")

ERROR:Arduino_c: Monster_MDP failed to translate
DEBUG:Arduino_c:Monster_MDP
stdout:

stderr:

DEBUG:Arduino_c:No JSON object could be decoded
DEBUG:Arduino_c:<type 'exceptions.ValueError'>
DEBUG:Arduino_c:  File "Tester.py", line 110, in runTest
    self.parser.parse(full_path)

  File "/mnt/c/Users/Dajin/Documents/GitHub/JFlapToCode/src/JFlapToCode.py", line 41, in parse
    self.parse_json( filename )

  File "/mnt/c/Users/Dajin/Documents/GitHub/JFlapToCode/src/JFlapToCode.py", line 68, in parse_json
    d = json.loads( raw_string )

  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)

  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())

  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")

ERROR:CSharp: Monster_MDP failed to translate
DEBUG:CSharp:Monster_MDP
stdout:

stderr:

DEBUG:CSharp:No JSON object could be decoded
DEBUG:CSharp:<type 'exceptions.ValueError'>
DEBUG:CSharp:  File "Tester.py", line 110, in runTest
    self.parser.parse(full_path)

  File "/mnt/c/Users/Dajin/Documents/GitHub/JFlapToCode/src/JFlapToCode.py", line 41, in parse
    self.parse_json( filename )

  File "/mnt/c/Users/Dajin/Documents/GitHub/JFlapToCode/src/JFlapToCode.py", line 68, in parse_json
    d = json.loads( raw_string )

  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)

  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())

  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")

ERROR:Unity: Monster_MDP failed to translate
DEBUG:Unity:Monster_MDP
stdout:

stderr:

DEBUG:Unity:No JSON object could be decoded
DEBUG:Unity:<type 'exceptions.ValueError'>
DEBUG:Unity:  File "Tester.py", line 110, in runTest
    self.parser.parse(full_path)

  File "/mnt/c/Users/Dajin/Documents/GitHub/JFlapToCode/src/JFlapToCode.py", line 41, in parse
    self.parse_json( filename )

  File "/mnt/c/Users/Dajin/Documents/GitHub/JFlapToCode/src/JFlapToCode.py", line 68, in parse_json
    d = json.loads( raw_string )

  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)

  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())

  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")

ERROR:UnitySimple: Monster_MDP failed to translate
DEBUG:UnitySimple:Monster_MDP
stdout:

stderr:

DEBUG:UnitySimple:No JSON object could be decoded
DEBUG:UnitySimple:<type 'exceptions.ValueError'>
DEBUG:UnitySimple:  File "Tester.py", line 110, in runTest
    self.parser.parse(full_path)

  File "/mnt/c/Users/Dajin/Documents/GitHub/JFlapToCode/src/JFlapToCode.py", line 41, in parse
    self.parse_json( filename )

  File "/mnt/c/Users/Dajin/Documents/GitHub/JFlapToCode/src/JFlapToCode.py", line 68, in parse_json
    d = json.loads( raw_string )

  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)

  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())

  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")

ERROR:UnityCompact: Monster_MDP failed to translate
DEBUG:UnityCompact:Monster_MDP
stdout:

stderr:

DEBUG:UnityCompact:No JSON object could be decoded
DEBUG:UnityCompact:<type 'exceptions.ValueError'>
DEBUG:UnityCompact:  File "Tester.py", line 110, in runTest
    self.parser.parse(full_path)

  File "/mnt/c/Users/Dajin/Documents/GitHub/JFlapToCode/src/JFlapToCode.py", line 41, in parse
    self.parse_json( filename )

  File "/mnt/c/Users/Dajin/Documents/GitHub/JFlapToCode/src/JFlapToCode.py", line 68, in parse_json
    d = json.loads( raw_string )

  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)

  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())

  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")

ERROR:C: Monster_MDP failed to translate
DEBUG:C:Monster_MDP
stdout:

stderr:

DEBUG:C:No JSON object could be decoded
DEBUG:C:<type 'exceptions.ValueError'>
DEBUG:C:  File "Tester.py", line 110, in runTest
    self.parser.parse(full_path)

  File "/mnt/c/Users/Dajin/Documents/GitHub/JFlapToCode/src/JFlapToCode.py", line 41, in parse
    self.parse_json( filename )

  File "/mnt/c/Users/Dajin/Documents/GitHub/JFlapToCode/src/JFlapToCode.py", line 68, in parse_json
    d = json.loads( raw_string )

  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)

  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())

  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")

ERROR:Cpp: Monster_MDP failed to translate
DEBUG:Cpp:Monster_MDP
stdout:

stderr:

DEBUG:Cpp:No JSON object could be decoded
DEBUG:Cpp:<type 'exceptions.ValueError'>
DEBUG:Cpp:  File "Tester.py", line 110, in runTest
    self.parser.parse(full_path)

  File "/mnt/c/Users/Dajin/Documents/GitHub/JFlapToCode/src/JFlapToCode.py", line 41, in parse
    self.parse_json( filename )

  File "/mnt/c/Users/Dajin/Documents/GitHub/JFlapToCode/src/JFlapToCode.py", line 68, in parse_json
    d = json.loads( raw_string )

  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)

  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())

  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")

ERROR:Python: Monster_MDP failed to translate
DEBUG:Python:Monster_MDP
stdout:

stderr:

DEBUG:Python:No JSON object could be decoded
DEBUG:Python:<type 'exceptions.ValueError'>
DEBUG:Python:  File "Tester.py", line 110, in runTest
    self.parser.parse(full_path)

  File "/mnt/c/Users/Dajin/Documents/GitHub/JFlapToCode/src/JFlapToCode.py", line 41, in parse
    self.parse_json( filename )

  File "/mnt/c/Users/Dajin/Documents/GitHub/JFlapToCode/src/JFlapToCode.py", line 68, in parse_json
    d = json.loads( raw_string )

  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)

  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())

  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")

ERROR:Dot: Monster_MDP failed to translate
DEBUG:Dot:Monster_MDP
stdout:

stderr:

DEBUG:Dot:No JSON object could be decoded
DEBUG:Dot:<type 'exceptions.ValueError'>
DEBUG:Dot:  File "Tester.py", line 110, in runTest
    self.parser.parse(full_path)

  File "/mnt/c/Users/Dajin/Documents/GitHub/JFlapToCode/src/JFlapToCode.py", line 41, in parse
    self.parse_json( filename )

  File "/mnt/c/Users/Dajin/Documents/GitHub/JFlapToCode/src/JFlapToCode.py", line 68, in parse_json
    d = json.loads( raw_string )

  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)

  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())

  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")

ERROR:Java: Monster_MDP failed to translate
DEBUG:Java:Monster_MDP
stdout:

stderr:

DEBUG:Java:No JSON object could be decoded
DEBUG:Java:<type 'exceptions.ValueError'>
DEBUG:Java:  File "Tester.py", line 110, in runTest
    self.parser.parse(full_path)

  File "/mnt/c/Users/Dajin/Documents/GitHub/JFlapToCode/src/JFlapToCode.py", line 41, in parse
    self.parse_json( filename )

  File "/mnt/c/Users/Dajin/Documents/GitHub/JFlapToCode/src/JFlapToCode.py", line 68, in parse_json
    d = json.loads( raw_string )

  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)

  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())

  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")

ERROR:Arduino: UnityChanFighter failed to translate
DEBUG:Arduino:UnityChanFighter
stdout:

stderr:

DEBUG:Arduino:No JSON object could be decoded
DEBUG:Arduino:<type 'exceptions.ValueError'>
DEBUG:Arduino:  File "Tester.py", line 110, in runTest
    self.parser.parse(full_path)

  File "/mnt/c/Users/Dajin/Documents/GitHub/JFlapToCode/src/JFlapToCode.py", line 41, in parse
    self.parse_json( filename )

  File "/mnt/c/Users/Dajin/Documents/GitHub/JFlapToCode/src/JFlapToCode.py", line 68, in parse_json
    d = json.loads( raw_string )

  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)

  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())

  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")

ERROR:Arduino_c: UnityChanFighter failed to translate
DEBUG:Arduino_c:UnityChanFighter
stdout:

stderr:

DEBUG:Arduino_c:No JSON object could be decoded
DEBUG:Arduino_c:<type 'exceptions.ValueError'>
DEBUG:Arduino_c:  File "Tester.py", line 110, in runTest
    self.parser.parse(full_path)

  File "/mnt/c/Users/Dajin/Documents/GitHub/JFlapToCode/src/JFlapToCode.py", line 41, in parse
    self.parse_json( filename )

  File "/mnt/c/Users/Dajin/Documents/GitHub/JFlapToCode/src/JFlapToCode.py", line 68, in parse_json
    d = json.loads( raw_string )

  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)

  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())

  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")

ERROR:CSharp: UnityChanFighter failed to translate
DEBUG:CSharp:UnityChanFighter
stdout:

stderr:

DEBUG:CSharp:No JSON object could be decoded
DEBUG:CSharp:<type 'exceptions.ValueError'>
DEBUG:CSharp:  File "Tester.py", line 110, in runTest
    self.parser.parse(full_path)

  File "/mnt/c/Users/Dajin/Documents/GitHub/JFlapToCode/src/JFlapToCode.py", line 41, in parse
    self.parse_json( filename )

  File "/mnt/c/Users/Dajin/Documents/GitHub/JFlapToCode/src/JFlapToCode.py", line 68, in parse_json
    d = json.loads( raw_string )

  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)

  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())

  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")

ERROR:Unity: UnityChanFighter failed to translate
DEBUG:Unity:UnityChanFighter
stdout:

stderr:

DEBUG:Unity:No JSON object could be decoded
DEBUG:Unity:<type 'exceptions.ValueError'>
DEBUG:Unity:  File "Tester.py", line 110, in runTest
    self.parser.parse(full_path)

  File "/mnt/c/Users/Dajin/Documents/GitHub/JFlapToCode/src/JFlapToCode.py", line 41, in parse
    self.parse_json( filename )

  File "/mnt/c/Users/Dajin/Documents/GitHub/JFlapToCode/src/JFlapToCode.py", line 68, in parse_json
    d = json.loads( raw_string )

  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)

  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())

  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")

ERROR:UnitySimple: UnityChanFighter failed to translate
DEBUG:UnitySimple:UnityChanFighter
stdout:

stderr:

DEBUG:UnitySimple:No JSON object could be decoded
DEBUG:UnitySimple:<type 'exceptions.ValueError'>
DEBUG:UnitySimple:  File "Tester.py", line 110, in runTest
    self.parser.parse(full_path)

  File "/mnt/c/Users/Dajin/Documents/GitHub/JFlapToCode/src/JFlapToCode.py", line 41, in parse
    self.parse_json( filename )

  File "/mnt/c/Users/Dajin/Documents/GitHub/JFlapToCode/src/JFlapToCode.py", line 68, in parse_json
    d = json.loads( raw_string )

  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)

  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())

  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")

ERROR:UnityCompact: UnityChanFighter failed to translate
DEBUG:UnityCompact:UnityChanFighter
stdout:

stderr:

DEBUG:UnityCompact:No JSON object could be decoded
DEBUG:UnityCompact:<type 'exceptions.ValueError'>
DEBUG:UnityCompact:  File "Tester.py", line 110, in runTest
    self.parser.parse(full_path)

  File "/mnt/c/Users/Dajin/Documents/GitHub/JFlapToCode/src/JFlapToCode.py", line 41, in parse
    self.parse_json( filename )

  File "/mnt/c/Users/Dajin/Documents/GitHub/JFlapToCode/src/JFlapToCode.py", line 68, in parse_json
    d = json.loads( raw_string )

  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)

  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())

  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")

ERROR:C: UnityChanFighter failed to translate
DEBUG:C:UnityChanFighter
stdout:

stderr:

DEBUG:C:No JSON object could be decoded
DEBUG:C:<type 'exceptions.ValueError'>
DEBUG:C:  File "Tester.py", line 110, in runTest
    self.parser.parse(full_path)

  File "/mnt/c/Users/Dajin/Documents/GitHub/JFlapToCode/src/JFlapToCode.py", line 41, in parse
    self.parse_json( filename )

  File "/mnt/c/Users/Dajin/Documents/GitHub/JFlapToCode/src/JFlapToCode.py", line 68, in parse_json
    d = json.loads( raw_string )

  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)

  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())

  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")

ERROR:Cpp: UnityChanFighter failed to translate
DEBUG:Cpp:UnityChanFighter
stdout:

stderr:

DEBUG:Cpp:No JSON object could be decoded
DEBUG:Cpp:<type 'exceptions.ValueError'>
DEBUG:Cpp:  File "Tester.py", line 110, in runTest
    self.parser.parse(full_path)

  File "/mnt/c/Users/Dajin/Documents/GitHub/JFlapToCode/src/JFlapToCode.py", line 41, in parse
    self.parse_json( filename )

  File "/mnt/c/Users/Dajin/Documents/GitHub/JFlapToCode/src/JFlapToCode.py", line 68, in parse_json
    d = json.loads( raw_string )

  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)

  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())

  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")

ERROR:Python: UnityChanFighter failed to translate
DEBUG:Python:UnityChanFighter
stdout:

stderr:

DEBUG:Python:No JSON object could be decoded
DEBUG:Python:<type 'exceptions.ValueError'>
DEBUG:Python:  File "Tester.py", line 110, in runTest
    self.parser.parse(full_path)

  File "/mnt/c/Users/Dajin/Documents/GitHub/JFlapToCode/src/JFlapToCode.py", line 41, in parse
    self.parse_json( filename )

  File "/mnt/c/Users/Dajin/Documents/GitHub/JFlapToCode/src/JFlapToCode.py", line 68, in parse_json
    d = json.loads( raw_string )

  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)

  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())

  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")

ERROR:Dot: UnityChanFighter failed to translate
DEBUG:Dot:UnityChanFighter
stdout:

stderr:

DEBUG:Dot:No JSON object could be decoded
DEBUG:Dot:<type 'exceptions.ValueError'>
DEBUG:Dot:  File "Tester.py", line 110, in runTest
    self.parser.parse(full_path)

  File "/mnt/c/Users/Dajin/Documents/GitHub/JFlapToCode/src/JFlapToCode.py", line 41, in parse
    self.parse_json( filename )

  File "/mnt/c/Users/Dajin/Documents/GitHub/JFlapToCode/src/JFlapToCode.py", line 68, in parse_json
    d = json.loads( raw_string )

  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)

  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())

  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")

ERROR:Java: UnityChanFighter failed to translate
DEBUG:Java:UnityChanFighter
stdout:

stderr:

DEBUG:Java:No JSON object could be decoded
DEBUG:Java:<type 'exceptions.ValueError'>
DEBUG:Java:  File "Tester.py", line 110, in runTest
    self.parser.parse(full_path)

  File "/mnt/c/Users/Dajin/Documents/GitHub/JFlapToCode/src/JFlapToCode.py", line 41, in parse
    self.parse_json( filename )

  File "/mnt/c/Users/Dajin/Documents/GitHub/JFlapToCode/src/JFlapToCode.py", line 68, in parse_json
    d = json.loads( raw_string )

  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)

  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())

  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")

